import dynamic from "next/dynamic";
import Head from "next/head";
import { Navbar, Querypannel } from "~/components";

const Viewer = dynamic(() => import("~/components/Viewer"), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="absolute top-14 h-[calc(100vh-3.5rem)] w-full overflow-hidden">
          <Viewer />
        </div>
        <Navbar />
        <Querypannel/>
      </main>
    </>
  );
}
