import Head from "next/head";
import ARViewer from "~/components/ARViewer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        lol
        <ARViewer height="100px" />
      </main>
    </>
  );
}
