import Head from "next/head";
import { GLTFViewer } from "xeokit-react/src";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <GLTFViewer canvasID="canvas-1" models={[sampleModel1]} />
      </main>
    </>
  );
}
